# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
    - 3.6
    - 3.7
    - 3.8
    - 3.9

env:
    - version=without_numpy
    - version=with_numpy

install:
    - if [[ $version == with_numpy ]]; then pip install numpy ; fi
    - python setup.py install
    - pip install codecov pytest

script:
    - cd tests
    - pytest
    - if [[ $version == with_numpy ]]; then coverage run --source=asteval test_asteval.py && coverage report -m ; fi

after_success:
    - if [[ $version == with_numpy ]]; then codecov ; fi
